const moods=[{name:'低落',icon:'🌧️',score:1},{name:'焦虑',icon:'🌪️',score:2},{name:'平静',icon:'🌤️',score:3},{name:'开心',icon:'☀️',score:4},{name:'充满能量',icon:'🌈',score:5}];
const labels=['学业','工作','人际关系','亲密关系','睡眠','身体状态','独处','生活小事'];
const $=id=>document.getElementById(id);let selected=2,tags=new Set(),entries=[],careCount=0,breathTimer=null,breathSeconds=0,audioContext=null;
try{const data=JSON.parse(localStorage.getItem('mind-island-v1')||'{}');entries=Array.isArray(data.entries)?data.entries.filter(e=>e&&Number.isInteger(e.mood)&&moods[e.mood]&&Array.isArray(e.tags)&&typeof e.note==='string'&&!isNaN(new Date(e.date))):[];careCount=Number(data.careCount)||0}catch(e){}
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.setItem('mind-island-v1',JSON.stringify({entries,careCount}));return true}catch(e){toast('浏览器存储不可用，请导出日记备份');return false}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');setTimeout(()=>$('toast').classList.remove('visible'),3000)}
function showPage(id){if(!['today','journal','insights','care'].includes(id))id='today';document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));history.replaceState(null,'','#'+id);render();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function drawMoods(){$('moods').innerHTML=moods.map((m,i)=>`<button class="mood ${selected===i?'selected':''}" aria-pressed="${selected===i}" onclick="selected=${i};drawMoods()"><b>${m.icon}</b>${m.name}</button>`).join('')}
function drawTags(){$('tags').innerHTML=labels.map(t=>`<button class="${tags.has(t)?'selected':''}" aria-pressed="${tags.has(t)}" onclick="toggleTag('${t}')">${t}</button>`).join('')}
function toggleTag(t){tags.has(t)?tags.delete(t):tags.add(t);drawTags()}
const suggestions=['现在可能有点难熬。允许自己先停一会儿，试着做一分钟自然呼吸，或者找一位信任的人聊聊。','事情堆在一起时，很容易感到紧绷。先把注意力放到一次呼吸上，再选出眼前最小的一件事。','平静也是值得收藏的时刻。听一会儿舒缓的声音，留意此刻让你感到踏实的小事。','很高兴你留住了这个好时刻。可以写下让你开心的小事，未来的自己也许会从中得到力量。','感受到你的活力了。可以把这份能量留给一次散步，也给自己留一点休息的空间。'];
$('save').onclick=()=>{const entry={id:Date.now(),date:new Date().toISOString(),mood:selected,intensity:Number($('energy').value),tags:[...tags],note:$('note').value.trim()};entries.unshift(entry);const saved=persist();$('resultTitle').textContent=saved?'已保存：'+moods[selected].name:'已暂存本次心情，请及时导出';$('resultText').textContent=suggestions[selected]+(tags.size?' 你提到了'+[...tags].join('、')+'，可以继续观察它们与你的感受有怎样的联系。':'');$('careReason').textContent='根据你最近的「'+moods[selected].name+'」心情：'+suggestions[selected];$('result').showModal();$('note').value='';tags.clear();drawTags();render()};
function render(){const dates=new Set(entries.map(e=>new Date(e.date).toLocaleDateString()));$('total').textContent=entries.length;$('days').textContent=dates.size;$('sessions').textContent=careCount;renderJournal();renderInsights()}
function renderJournal(){const q=$('search').value.toLowerCase();const list=entries.filter(e=>(e.note+' '+e.tags.join(' ')+' '+moods[e.mood].name).toLowerCase().includes(q));$('journalList').innerHTML=list.length?list.map(e=>`<article class="card entry"><div class="entry-head"><h2>${moods[e.mood].icon} ${moods[e.mood].name} <small>强度 ${e.intensity}/10</small></h2><button class="delete" onclick="deleteEntry(${e.id})">删除</button></div><span class="muted">${new Date(e.date).toLocaleString('zh-CN')}</span><p>${escapeHtml(e.note||'今天没有写文字，但我认真看见了自己的感受。')}</p><div>${e.tags.map(t=>`<span class="pill">${escapeHtml(t)}</span>`).join(' ')}</div></article>`).join(''):`<div class="empty">${q?'没有找到匹配的日记。':'还没有日记。去「今日心情」留下第一条记录吧。'}</div>`}
function deleteEntry(id){if(!confirm('确定删除这条日记？建议先导出备份。'))return;entries=entries.filter(e=>e.id!==id);persist();render();toast('日记已删除')}
function renderInsights(){const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const rows=entries.filter(e=>new Date(e.date).toLocaleDateString()===d.toLocaleDateString());return {label:(d.getMonth()+1)+'/'+d.getDate(),avg:rows.length?rows.reduce((s,e)=>s+moods[e.mood].score,0)/rows.length:null}});$('chart').innerHTML=days.map(d=>`<div class="chart-col"><span>${d.avg?d.avg.toFixed(1):'—'}</span><div class="bar" style="height:${d.avg?d.avg*25:3}px;background:${d.avg?'#90b59b':'#e7ebe4'}"></div><span>${d.label}</span></div>`).join('');const counts={};entries.forEach(e=>e.tags.forEach(t=>counts[t]=(counts[t]||0)+1));const sorted=Object.entries(counts).sort((a,b)=>b[1]-a[1]);$('triggers').innerHTML=sorted.length?sorted.map(([t,n])=>`<div class="trigger">${escapeHtml(t)} <span style="float:right">${n} 次</span><div class="track"><i style="width:${n/entries.length*100}%"></i></div></div>`).join(''):'<p class="muted">记录时选择触发因素，这里会帮你整理。</p>';if(entries.length){const top=sorted[0];$('insightTitle').textContent=top?'「'+top[0]+'」是你经常提到的生活片段':'你已经开始倾听自己的感受';$('insightText').textContent=top?`在 ${entries.length} 条记录中，你有 ${top[1]} 次提到「${top[0]}」。这只是共同出现的线索，不代表它是情绪的原因。下次可以写下具体发生的事，以及自己希望得到的支持。`:'继续为情绪添加标签，帮助自己逐渐发现生活与感受之间的联系。'}else{$('insightTitle').textContent='每一条记录，都是了解自己的起点';$('insightText').textContent='开始记录后，这里会根据你的情绪与标签呈现个性化观察。'}}
function toggleBreathing(){if(breathTimer){clearInterval(breathTimer);breathTimer=null;$('breathCircle').classList.remove('breathing');$('breathCircle').textContent='随时再回来';$('breathBtn').textContent='开始呼吸练习';return}breathSeconds=0;$('breathCircle').classList.add('breathing');$('breathCircle').textContent='轻轻吸气';$('breathBtn').textContent='停止练习';breathTimer=setInterval(()=>{breathSeconds++;$('breathCircle').textContent=(breathSeconds%10<4?'轻轻吸气':'缓缓呼气')+' · '+(60-breathSeconds)+'s';if(breathSeconds>=60){toggleBreathing();completeCare('一分钟呼吸')}},1000)}
async function toggleSound(){if(audioContext){await audioContext.close();audioContext=null;$('soundBtn').textContent='播放舒缓声音';return}try{audioContext=new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();[130.81,196,261.63,329.63].forEach(f=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=f;gain.gain.value=.025;osc.connect(gain);gain.connect(audioContext.destination);osc.start()});$('soundBtn').textContent='暂停声音'}catch(e){audioContext=null;toast('此浏览器暂不支持声音播放')}}
function completeCare(name){careCount++;persist();render();toast('完成'+name+'，谢谢你照顾自己。')}
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),entries:entries.map(e=>({...e,moodName:moods[e.mood].name})),careCount},null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='心屿-我的情绪日记.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('date').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});drawMoods();drawTags();showPage(location.hash.slice(1)||'today');
